### PR TITLE
support dynamic loading of sqlite3 sha3 extension

### PR DESCRIPTION
**Pull request by larskuhtz**
Add support building `c/shathree.c` as dynamically loadable SQLite3 extension.

### CODE REVIEW

**Comment by chessai** [comment]
is there some documentation on how this works? how can i test it?

**Comment by larskuhtz** [comment]
> is there some documentation on how this works? how can i test it?

The following examples are for MacOSX.

If needed, install sqlite3 version that supports extension loading via home-brew

```bash
brew update
brew install sqlite3
export PATH="/opt/homebrew/opt/sqlite/bin:$PATH"
sqlite3 <<< '.dbconfig'
```

Download (from this PR) and compile extension:

```bash
curl -O https://raw.githubusercontent.com/kadena-io/chainweb-node/8d94bdb49810a9126b714f631c5a1e78e086898f/c/shathree.c
gcc -shared -g -fPIC -dynamiclib shathree.c -o shathree.dylib -I$(brew --prefix sqlite)/include -L$(brew --prefix sqlite)/lib -lsqlite3
```

Use extension:

```bash
sqlite3 -cmd '.load shathree.dylib' <<< 'SELECT hex(sha3(1,2,3))'
```

**Comment by chessai** [comment]
On Linux, the instructions for building change to this (linker and include args for sqlite path may be unnecessary depending on distro)
```
gcc -shared -g -fPIC shathree.c -o shathree.so -I$(/path/to/sqlite-dev)/include -L$(/path/to/sqlite-dev)/lib -lsqlite3
```

And then you have to load the extension slightly differently, including the path (`./`):
```
sqlite3 -cmd '.load ./shathree.so' <<< 'SELECT hex(sha3(1,2,3))'
```

**Review by chessai — APPROVED** [review]

**Comment by chessai** [comment]
I've tested this extensively and it works. Merging.

**Pull request merged**
