### PR TITLE
Adjust catchup step size and far ahead threshold

### PR DESCRIPTION
**Pull request by larskuhtz**

### CODE REVIEW

**Comment by jwiegley** [comment]
Hi @larskuhtz, can you say more to explain the reason for this change, and why these are now the right numbers to use?

**Comment by enobayram** [comment]
@larskuhtz I've tried deploying this version to a personal node with an old database, but it failed to make any progress during the 20 minutes I've watched it.

**Comment by chessai** [comment]
> @larskuhtz I've tried deploying this version to a personal node with an old database, but it failed to make any progress during the 20 minutes I've watched it.

Lars and I were testing this with my node, and it failed to make progress for 3 hours, unfortunately. So this is still a WIP.

**Comment by chessai** [comment]
Catchup is no longer stalled. However, it seems that it's about 0.85 cuts/s slower.

**Review by chessai — APPROVED** [review]

**Pull request merged**
