### PR TITLE
Add quasiquoter for time constants

### PR DESCRIPTION
**Pull request by mightybyte**

### CODE REVIEW

**Comment by mightybyte** [comment]
Note that the target of this PR is @fosskers other branch for which there is an open PR to master.

**Comment by mightybyte** [comment]
Yes, I confirmed the outputs.  This second commit `77fad51` generates exactly the same values that were there before.

**Comment by larskuhtz** [comment]
I think, we should still write a small test case to protect against regressions in the time library. But we can do that later.

**Comment by mightybyte** [comment]
Agreed.

**Pull request merged**
